### ISSUE TITLE
Python write support

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#6564]
### Feature Request / Improvement

This is a placeholder ticket for implementing write support for PyIceberg.

Since we don't want PyIceberg to write the actual data, and only handle the metadata part of the Iceberg table format, we need to get an overview of the frameworks we most likely want to integrate with (PyArrow, Dask (fastparquet?), etc).

I would suggest the following first steps to keep it simple: Write using PyArrow (since that's the most commonly used FileIO) and start with unpartitioned tables.

What we need:

- [x] Avro write support: https://github.com/apache/iceberg/issues/7255
- [ ] Write files and extract statistics: https://github.com/apache/iceberg/issues/7256
- [ ] Ability to alter the Manifest JSON: https://github.com/apache/iceberg/issues/7257
- [x] Proper integration tests between Java and Python: https://github.com/apache/iceberg/pull/6398

### Query engine

None

**Comment by nazq** [comment]
Keen to see this one progress, especially w pyarrow. Cc @asheeshgarg. Happy to help out

**Comment by Hayder-Aziz-cardano** [comment]
it would be really nice to get it working with polars (which utilises pyarrow / connectorx) as it provides the possibility of running execution services without large monolithic services like hive or spark.

**Comment by marsupialtail** [comment]
A great intermediate step would be to simply allow an engine like Polars/Pandas/Quokka to write out the actual parquet files in a given location with provided names that don't conflict with existing files, and then "register" those Parquet files in the iceberg metadata file.

**Comment by corleyma** [comment]
> One thing we can use is directly leverage Java APIs using PY4J or JYPE to call the underlying API. This will reduce the maintenance at two places.

From my perspective at least, any solution that makes the JVM a dependency for users of the Python API is a poor solution.

**Comment by Matthieusalor** [comment]
Regarding statistics of written files, the write_to_dataset and write_dataset functions of pyarrow are providing a file_visitor argument that allows to retrieve the path and metadata of each written file.

The metadata object is https://arrow.apache.org/docs/python/generated/pyarrow.parquet.FileMetaData.html 
It allows to retrieve each row group statistics https://arrow.apache.org/docs/python/generated/pyarrow.parquet.RowGroupMetaData.html#pyarrow.parquet.RowGroupMetaData

**Comment by Fokko** [comment]
@Matthieusalor Thanks for the suggestion. I was looking into the `metadata_collector`: https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_metadata.html It looks like we can leverage this to collect the metadata during the write.

**Comment by luancaarvalho** [comment]
Hello everyone! 
I was wondering if there have been any updates recently. Additionally, is there a roadmap available that shows if any contributors are currently working on the feature I am interested in? 
Thank you!

**Comment by corleyma** [comment]
I dunno about roadmap, but there are some outstanding PRs in different stages of development that are directly relevant to this feature and are linked/referenced by the task list in the issue body.

Specifically, these both seem worth following up on if you're looking to contribute:
https://github.com/apache/iceberg/pull/7831
https://github.com/apache/iceberg/pull/8012

Also, this repo organizes issues into [milestones](https://github.com/apache/iceberg/milestones); there you can see milestones for the next two planned releases of pyiceberg and the issues that are currently assigned to each.

**Comment by Fokko** [comment]
Migrated to the new repository: https://github.com/apache/iceberg-python/issues/23
