### ISSUE TITLE
Partition stats task tracker

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#8450]
Mailing list discussion archive: https://lists.apache.org/thread/5pzyvncvz6td1vmf02o02ncknbvbzrs7
Design Doc: https://docs.google.com/document/d/1vaufuD47kMijz97LxM67X8OX-W2Wq7nmlz3jRo8J5Qk/edit?usp=sharing

- [x] https://github.com/apache/iceberg/issues/8451
- [x] https://github.com/apache/iceberg/issues/8452
- [x] https://github.com/apache/iceberg/issues/8457
- [x] https://github.com/apache/iceberg/pull/9409
- [x] https://github.com/apache/iceberg/issues/9336
- [x] https://github.com/apache/iceberg/pull/11146
- [x] https://github.com/apache/iceberg/pull/11216
- [x] https://github.com/apache/iceberg/pull/12629
- [x] https://github.com/apache/iceberg/pull/12450
- [x] https://github.com/apache/iceberg/pull/13480
- [x] https://github.com/apache/iceberg/pull/13425

Additional improvement from the community

- [ ] https://github.com/apache/iceberg/issues/11083

Good to have future enhancements

- [ ] https://github.com/apache/iceberg/issues/8458

**Comment by ajantha-bhat** [comment]
Closing this task as completed today. V4 and future work can still be tracked in this even after closing it.

**Comment by sopel39** [comment]
@ajantha-bhat is https://github.com/apache/iceberg/issues/11083 still valid after this is closed?

**Comment by ajantha-bhat** [comment]
@sopel39: Still valid and I think @gaborkaszab had new proposal for this. 

I closed this issue tracker as we can track from subtask directly now.
